language_whitelist = ['cs']

[dataset]
noisy = '/home/jirka/asr_dataset/noisy'
clean = '/home/jirka/asr_dataset/clean'
ambient = '/home/jirka/asr_dataset/ambient'
speakers = '/home/jirka/asr_dataset/speakers'


[weights]
vocab = './weights/vocab.txt'
asr = './weights/asr.safetensors'
voice_reconstruction = './weights/voice_reconstruction.safetensors'
voiceprint = './weights/voiceprint.safetensors'
yoho = './weights/yoho.safetensors'

[hyperparameters.tokenizer]
max_token_length = 32
vocab_size = 32000

[hyperparameters.transcribe_pretrain]
learning_rate = 0.003
batch_size = 64
updates = 250000
speechless_sample_ratio = 0.1

[hyperparameters.reconstruct_pretrain]
learning_rate = 0.003
batch_size = 64
updates = 250000

[hyperparameters.voiceprint_finetune]
learning_rate = 0.003
batch_size = 128
updates = 100000

[hyperparameters.transcribe_finetune]
learning_rate = 0.003
batch_size = 64
updates = 250000
speechless_sample_ratio = 0.1
